export type TextProps =
  | "Display"
  | "H1"
  | "H2"
  | "H3"
  | "H4"
  | "BodyBold"
  | "Body"
  | "LabelBold"
  | "Label"
  | "LabelLight"
  | "Navigation";

export type FontWeight = 700 | 600 | 500 | 400;

export type ShadowType = "Large" | "Medium" | "Small";

export type IconType =
  | "App_List"
  | "Arrow_Down"
  | "Arrow_Left"
  | "Arrow_Right"
  | "Arrow_Up"
  | "Check_Button"
  | "Chevron_Down"
  | "Chevron_Left"
  | "Chevron_Right"
  | "Chevron_Up"
  | "ChoresBathroom"
  | "ChoresDish"
  | "ChoresEntrance"
  | "ChoresGarden"
  | "ChoresHousit"
  | "ChoresKitchen"
  | "ChoresLaundry"
  | "ChoresLivingroom"
  | "ChoresOffice"
  | "ChoresToilet"
  | "ChoresTrash"
  | "ChoresVacuum"
  | "Circle_Information"
  | "Circle_Question"
  | "Close_Button"
  | "Delete_Button"
  | "Dots_Horizontal"
  | "Dots_Vertical"
  | "Edit_Button"
  | "Eye_Close"
  | "Eye_Open"
  | "Hamburger"
  | "Icon_Chore"
  | "Icon_Event"
  | "Icon_Finance"
  | "Icon_Food"
  | "Icon_Home"
  | "Icon_Money"
  | "Kitchen"
  | "Laundry"
  | "Like_Button"
  | "Like_Button_Filled"
  | "Livingroom"
  | "Lock_Close"
  | "Lock_Open"
  | "Logo_Main"
  | "Person_Add"
  | "Person"
  | "Plus_Button"
  | "Settings"
  | "Toilet"
  | "TriangleDown"
  | "Vacuum";

export type ChipSizeType = "Large" | "Medium" | "Small" | "XSmall";
